<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kindle Books</name>
   <tag></tag>
   <elementGuidId>4dc440aa-c4cc-4174-aa73-943ab81fc926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba85c360-fab9-4420-a5cf-f6789bea3fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Kindle-eBooks/b/?ie=UTF8&amp;node=154606011&amp;ref_=nav_cs_kindle_books</value>
      <webElementGuid>379a31e5-732e-4f01-b1a9-e384a1230ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>b1a839d4-9a7c-44f9-bed9-38b0aad2e688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6970c58-8ac6-4859-a63d-c49570fed5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>e672a058-bebe-4d4a-a2f3-c8c8e55fa505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_9</value>
      <webElementGuid>33677a9e-ab66-47cb-8e92-d0d787b61941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_kindle_books</value>
      <webElementGuid>9030f496-70e5-40bc-9c27-f2e78ce63a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>fsn917-hd3v0o-gsv349-hr44fv</value>
      <webElementGuid>7d868c2c-ca9c-4452-b16b-95b839bc4823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kindle Books</value>
      <webElementGuid>10b2d13f-9254-46d5-83a5-a970c91abd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>16635359-fc2b-4fd3-963c-329f182f08fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[10]</value>
      <webElementGuid>17653b5c-3d79-4330-a6a7-4145188f4353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kindle Books')]</value>
      <webElementGuid>83a1cc65-95c6-427c-a9a3-f517c328c57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Household, Health &amp; Baby Care'])[1]/following::a[1]</value>
      <webElementGuid>3275d962-585f-4d34-b4ed-582ccaa2bb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pharmacy'])[1]/following::a[2]</value>
      <webElementGuid>26718257-d5c7-4138-8f5a-ed0da9a67e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop By Interest'])[1]/preceding::a[1]</value>
      <webElementGuid>3e35fc6c-47a9-4b65-8403-cf784d216b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupons'])[1]/preceding::a[2]</value>
      <webElementGuid>c5f8873f-35a6-472d-bde8-c918ae207487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kindle Books']/parent::*</value>
      <webElementGuid>c09ebda6-a24f-45ec-a0c7-58967a7e2ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Kindle-eBooks/b/?ie=UTF8&amp;node=154606011&amp;ref_=nav_cs_kindle_books')]</value>
      <webElementGuid>48c2deac-c649-48b6-aceb-fbf6b164493f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[10]</value>
      <webElementGuid>139f96df-4573-4e88-88af-f95059db4610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Kindle-eBooks/b/?ie=UTF8&amp;node=154606011&amp;ref_=nav_cs_kindle_books' and (text() = 'Kindle Books' or . = 'Kindle Books')]</value>
      <webElementGuid>7104b7a1-2da5-419d-a169-2a74bf95cc26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
