<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mothers Day Gifts</name>
   <tag></tag>
   <elementGuidId>e2f694b4-82f7-428d-b052-f68173ef7e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-events-mday']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-events-mday</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>017c60a7-5211-44f7-b972-85163cf0d6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-events-mday</value>
      <webElementGuid>33b64de2-0649-4a5c-9512-aaeb82939626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/b?node=120785584011&amp;ref_=nav_cs_events_mday</value>
      <webElementGuid>0fca880c-f579-40fd-8961-ecfeaaf8cca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>7e9bcbcf-0c8d-4bf7-a74f-45d2debd9567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a6b4edf-096f-4d07-9133-6139ef39ed11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>490bff32-61f8-4719-a804-211115cab2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_0</value>
      <webElementGuid>c4110f12-c22b-47da-ac33-551db7b4e1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_events_mday</value>
      <webElementGuid>1a1da95a-151b-4d99-9c2b-0433fdc72c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>ua0kza-ujq8v1-hr0igp-gfhxhx</value>
      <webElementGuid>d8b1a0c6-e878-4216-8e19-405ea295a1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mother's Day Gifts</value>
      <webElementGuid>a68c71c2-fe2a-4027-ac39-e901b1a4ab76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-events-mday&quot;)</value>
      <webElementGuid>abf097a2-6a1e-4bc5-a617-943d5378098b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-events-mday']</value>
      <webElementGuid>1035e8b5-8b01-4d7e-885d-3e91209318f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a</value>
      <webElementGuid>491beac2-6ed1-45b9-b2f2-ef5e79ab9aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::a[1]</value>
      <webElementGuid>c118e023-0ffb-41d6-876b-5a6a39f06f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View fullhistory'])[1]/following::a[2]</value>
      <webElementGuid>a4ef23a5-17cb-4ece-a5d9-289924e22b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disability Customer Support'])[1]/preceding::a[1]</value>
      <webElementGuid>b477bd10-c152-4aae-b6cf-155d6ca30bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Care'])[1]/preceding::a[2]</value>
      <webElementGuid>c9cc3667-3545-4413-9b72-2f6c9d414aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/b?node=120785584011&amp;ref_=nav_cs_events_mday')]</value>
      <webElementGuid>a85cefe3-d133-4a4d-974b-3fcf90f7968b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/a</value>
      <webElementGuid>e2fa3099-f87b-405e-8385-eca70fe246ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-events-mday' and @href = '/b?node=120785584011&amp;ref_=nav_cs_events_mday' and (text() = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;) or . = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;))]</value>
      <webElementGuid>b9b3694a-86f0-4065-b569-5292bd0d2e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
