<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mothers Day Gifts</name>
   <tag></tag>
   <elementGuidId>b445f151-a207-4f44-ab58-82b9ac263273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-events-mday']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-events-mday</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7062c20-1216-48a6-801a-2709a7d66f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-events-mday</value>
      <webElementGuid>34ccce3e-7410-4b13-a3d7-08535fe8a29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/b?node=120785584011&amp;ref_=nav_cs_events_mday</value>
      <webElementGuid>f92e286c-e94a-4d22-ae66-0f5f0895c373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>75804d03-be83-425e-bcd3-a63d2c6dde0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>65ef0902-30c1-4d40-919d-693c2e11ac93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>e230b7f8-49da-449e-aadd-d60acd7eccb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_0</value>
      <webElementGuid>9aeccd48-9cad-4636-af6b-f997753401ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_events_mday</value>
      <webElementGuid>8507c60d-12db-47c2-b1e8-b380299ea9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>evnrpj-b1qdsf-vd7qh2-gn7izg</value>
      <webElementGuid>0a7e4eba-0f55-4db1-a18e-8bf47566d252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mother's Day Gifts</value>
      <webElementGuid>d2512f52-3265-4e2b-bf58-f9626d456584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-events-mday&quot;)</value>
      <webElementGuid>323b59f7-e9f9-4d93-bf6c-2cf6b9e4cbb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-events-mday']</value>
      <webElementGuid>c55afc94-a644-4a10-bcb6-ae7721bff696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a</value>
      <webElementGuid>788b0f7d-4b8f-49a5-b390-798974471185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::a[1]</value>
      <webElementGuid>087db4cb-94dc-4a4e-8dac-11a069641077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View fullhistory'])[1]/following::a[2]</value>
      <webElementGuid>a7865cf4-2b04-444f-b429-89b6dfbda32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disability Customer Support'])[1]/preceding::a[1]</value>
      <webElementGuid>92f5976f-220b-448d-a2dc-de004f13bb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Care'])[1]/preceding::a[2]</value>
      <webElementGuid>51255a28-37c6-4c4a-af45-f13bdc29b839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/b?node=120785584011&amp;ref_=nav_cs_events_mday')]</value>
      <webElementGuid>0a2b2090-c78d-4843-b6d2-8d666821dcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/a</value>
      <webElementGuid>f807b590-0f63-4003-adec-a58c91910382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-events-mday' and @href = '/b?node=120785584011&amp;ref_=nav_cs_events_mday' and (text() = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;) or . = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;))]</value>
      <webElementGuid>b431fdcf-ce5c-4d52-b0fe-831a6f03d073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
