<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mothers Day Gifts</name>
   <tag></tag>
   <elementGuidId>1c3a9bfb-1035-47e8-a930-7ec8d983ca67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-events-mday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-events-mday']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'nav-events-mday' and @href = '/b?node=120785584011&amp;ref_=nav_cs_events_mday' and (text() = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;) or . = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mother's Day Gifts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5eaeca86-52ed-4a02-92c6-41283dcbaab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-events-mday</value>
      <webElementGuid>83066ad5-f7dd-40e6-a9e6-56d80e5940d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/b?node=120785584011&amp;ref_=nav_cs_events_mday</value>
      <webElementGuid>9b2be694-8ca2-4b36-8057-57b38f69e582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>8251237f-4a56-4bdd-82e3-52a87e7ebd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b871578-b05c-4ce9-a59b-dd44e7e015db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>4996c50e-f088-45cc-a450-aba8ff5cb1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_0</value>
      <webElementGuid>6853b94b-ef8b-4ddc-a15f-d986bf94ba86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_events_mday</value>
      <webElementGuid>9d341623-6961-4301-9927-0a318fc01841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>h2dqrb-rsws5y-fh8e90-r2prae</value>
      <webElementGuid>ca482054-383a-43c8-bedd-866239133c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mother's Day Gifts</value>
      <webElementGuid>8077f568-1d1c-480f-a5c7-b0792c19bb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-events-mday&quot;)</value>
      <webElementGuid>f3da6b58-2596-4b27-87d0-0b2563ab53fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-events-mday']</value>
      <webElementGuid>3e352698-fd0a-4e98-b115-8e9f1b5a351f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a</value>
      <webElementGuid>5e4a26f1-451c-47f0-83df-6f5876909771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::a[1]</value>
      <webElementGuid>49a5d8f9-93b3-4f47-86d7-1c2070581e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore more Medical Care'])[1]/following::a[2]</value>
      <webElementGuid>8e95e6c2-fbc3-4fe5-a2b0-5162a976bef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disability Customer Support'])[1]/preceding::a[1]</value>
      <webElementGuid>10c2af62-589e-4a2f-9109-a1ceb09b0e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Care'])[1]/preceding::a[2]</value>
      <webElementGuid>d4911629-fa7a-43ab-aff7-83184fb7449d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/b?node=120785584011&amp;ref_=nav_cs_events_mday')]</value>
      <webElementGuid>305253ca-6c4c-4a55-a328-8920affce228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/a</value>
      <webElementGuid>0738668f-73e9-4b7b-b56c-b2f7d565446d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-events-mday' and @href = '/b?node=120785584011&amp;ref_=nav_cs_events_mday' and (text() = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;) or . = concat(&quot;Mother&quot; , &quot;'&quot; , &quot;s Day Gifts&quot;))]</value>
      <webElementGuid>447d3332-942e-4d6e-bdcc-991ad14f2cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
